### ISSUE TITLE
Out of order test method execution

### ISSUE THREAD

**Issue by Alastairm** [hlaueriksson/LoFuUnit#5] opened 2021-05-28 03:39 UTC
When I have >12 tests in a class a test will execute its methods out of order.

Output:
```
Test 10
	test method 7
	test method 1
	test method 2
	test method 3
	test method 4
	test method 5
	test method 6
```

Code:
```
public class LofuOutOfOrder: LoFuTest, IDisposable
    {


        public LofuBroken(ITestOutputHelper output) : base(output)
        {

        }

        [Fact]
        public async Task Test_1()
        {
            async Task test_method_1() {}
            async Task test_method_2() {}
            async Task test_method_3() {}
            async Task test_method_4() {}
            async Task test_method_5() {}
            async Task test_method_6() {}
            async Task test_method_7() { }
        }

        [Fact]
        public async Task Test_2()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }

        [Fact]
        public async Task Test_3()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }

        [Fact]
        public async Task Test_4()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }

        [Fact]
        public async Task Test_5()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }

        [Fact]
        public async Task Test_6()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }

        [Fact]
        public async Task Test_7()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }

        [Fact]
        public async Task Test_8()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }

        [Fact]
        public async Task Test_9()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }

        [Fact]
        public async Task Test_10()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }

        [Fact]
        public async Task Test_11()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }

        [Fact]
        public async Task Test_12()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }

        [Fact]
        public async Task Test_13()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }
        [Fact]
        public async Task Test_14()
        {
            async Task test_method_1() { }
            async Task test_method_2() { }
            async Task test_method_3() { }
            async Task test_method_4() { }
            async Task test_method_5() { }
            async Task test_method_6() { }
            async Task test_method_7() { }
        }

        public void Dispose()
        {

        }
    }
```

**Comment by hlaueriksson** [comment] 2021-05-28 06:57
Hi @Alastairm, thanks for reporting this issue.
I'll have to investigate this.

**Comment by hlaueriksson** [comment] 2021-05-28 18:34
This is really strange.

I can confirm that this happened for me with `LoFuUnit.Xunit` and these versions:

```csproj
    <PackageReference Include="LoFuUnit.Xunit" Version="1.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
```

However, after I bump `Microsoft.NET.Test.Sdk` and `xunit.runner.visualstudio` this issue disappeared:

```csproj
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
```

Now, even if I revert back to the previous versions, the execution is still in order.
Issue fixed, but I don't know how.

I could not reproduce this issue with `NUnit` or `MSTest`.

**Comment by hlaueriksson** [comment] 2021-05-28 18:41
What versions do you use @Alastairm?
Can you try with the latest versions? Like here c34d67c

**Comment by Alastairm** [comment] 2021-05-31 00:53
Thanks for the prompt reply @hlaueriksson, I've bumped Microsoft.NET.Test.Sdk to 16.10 (was 16.9.4), xunit.runner.visualstudio was already on 2.4.3 and the issue is still occurring.

**Comment by hlaueriksson** [comment] 2021-05-31 19:22
I'm sorry to report that `LoFuUnit` cannot guarantee the order in which the test functions are executed.

The base class for tests invokes [Type.GetMethods](https://docs.microsoft.com/en-us/dotnet/api/system.type.getmethods?view=net-5.0#System_Type_GetMethods_System_Reflection_BindingFlags_) to find the local functions to use in a test method:

* [Assert](https://github.com/hlaueriksson/LoFuUnit/blob/master/src/LoFuUnit/LoFuTest.cs#L44)
* [AssertAsync](https://github.com/hlaueriksson/LoFuUnit/blob/master/src/LoFuUnit/LoFuTest.cs#L66)

The docs from Microsoft states:

> The GetMethods method does not return methods in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which methods are returned, because that order varies.

So, when the test functions happens to execute in the correct order you are just lucky.

**Comment by hlaueriksson** [comment] 2021-05-31 19:45
I updated the [docs](https://github.com/hlaueriksson/LoFuUnit#tests-%EF%B8%8F):

> The invocations will probably occur in the order that the test functions are declared, but it's not guaranteed. Do not write tests that depend on the order of test function execution.

**Comment by hlaueriksson** [comment] 2021-06-04 20:47
@Alastairm thanks for the PR!

Version `1.3.0` of LoFuUnit is now released with your fix included 🥳

**Closed as completed** 2021-06-10 08:18 UTC
Labels: bug
